config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :categories, only: [:show] do
    get 'themes/random'
    
  end
  resources :themes, only: [:show] do
    get 'questions/random'
    
  end
  get 'pages/top'
  get 'pages/about'
  get 'pages/usage'
  get 'pages/start'
  get 'pages/game'
  get 'pages/question1'
  get 'pages/question2'
  get 'pages/question3'
  get 'pages/deadlock'
  get 'pages/deeply'
  get 'pages/reflection'
  get 'pages/reflection2'
  get 'pages/close'
  get 'pages/future'
  get 'pages/shiritori'
  get 'pages/philo'
  get 'pages/warmup'
  get 'categories/random'
  get 'questions/question1'
  root to: 'pages#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :themes 
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
    belongs_to :category
    has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end

  def about
  end

  def usage
  end

  def start
  end

  def game
  end

  def question1
  end

  def question2
  end

  def question3
  end

  def deadlock
  end

  def deeply
  end

  def reflection
  end

  def reflection2
  end

  def close
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def random
     theme = Theme.find(params[:theme_id])
    @question = theme.questions.all.sample
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def random
    category = Category.find(params[:category_id])
    @theme = category.themes.all.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/categories/random.html.erb
<h1><%= @category.name %></h1>

app/views/categories/show.html.erb
<h1>カテゴリ<%= @category.name %></h1>

<table>
    <thead>
        <tr>
            <td>テーマid</td>
            <td>テーマ名</td>
            <td>質問1</td>
            <td>質問2</td>
            <td>質問3</td>
        </tr>
    </thead>
    <tbody>
        <% @category.themes.each do |theme| %>
        <tr>
            <td><%= theme.id %></td>
            <td><%= theme.name %></td>
            <% theme.questions.each do |question| %>
            <td><%= question.name %><%= question.id %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to 'ランダムテーマ', category_themes_random_path(@category) %></p>

app/views/pages/about.html.erb
<h2>わたしたちの思い</h2>

<div class="img">
    <img class="about-img omoi" src="/akushu.jpg">
</div>
<h4>身近な人と、心を開いて、落ち着いて話し合うために</h4>
</br>
<div class="container container-m">
    <div class="card-deck">
        <div class="card">
            <div class="card-body">

                <h2 class="card-title">おうちの人へ</h2>
                <h5 class="card-text">● 進路は子ども自身の問題</h5>
                <h5 class="card-text">● 親の価値観を押し付けずに</h5>
                <h5 class="card-text">● 親の価値観も掘り下げて伝えて</h5>
                <p class="card-text">

                    子どもの進路は親にとって、大きな関心事ですが、子どもの進路選択の結果は、子ども自身が責任を負っていくものです。</br>
                    親の価値観を押し付けず、子どもが自分で考え決断することをサポートしていきましょう。</br>

                    また、親が自分の考えを話すパートでは、茶化したり誤魔化したりせず、真剣に掘り下げて考えてみてください。</br>
                    親の価値観、人生観、職業観を聞くのは、子どもにとって貴重な機会です。
                    この時間が充実した時間となるようサポートしていきます。</p>
            </div>
        </div>
        <div class="card">

            <div class="card-body">
                <h2 class="card-title">子どものみなさんへ</h2>
                <h5 class="card-text">● 自分の考えを整理してみて</h5>
                <h5 class="card-text">● 恥ずかしがらず諦めずに伝える</h5>
                <h5 class="card-text">● 親の考え方も理解しようとする</h5>
                <p class="card-text">
                    自分の進路についてはっきりイメージしている人、できていない人。どちらもいったん進路のことは忘れて、自分の考えを家族に伝えてみましょう。</br>

                    親と考えが違っていたとしても、分かり合えないとすぐにあきらめるのではなく、なにが違うのか、どうして相手はそう考えるのか聞いてみましょう。
                    親には親がそう考える理由があります。</br>
                    また自分はなぜそう考えるのか親に伝えてみましょう。</br>
                    完全に理解することはできなくても、今までよりお互いを尊重して接することができるようになると思います。
                </p>
            </div>
        </div>

    </div>
</div>
</br>
<div class="img">
    <img class="about-img" src="/nonbiri.jpg">
</div>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <div class="top-btn">
                <%= link_to 'トップページへ', pages_top_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>
        <div class="col-md-6 warm">
            <div class="top-btn">
                <%= link_to '使いかた', pages_usage_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>

    </div>
</div>

app/views/pages/close.html.erb
<h2>終了</h2>
<div class="img">
    <img class="about-img" src="/love.jpg">
</div>
</br>

<div class="container container-m">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <div class="reflection2">
                <p>お疲れさまでした。</br>
                    話し手を交代して、次の話し手の対話ゲームを開始してください。</br>
                    全員が話し手を終わらせたら、次のコースへ進んでください。</p>

                <div class="top-btn">
                    <%= link_to '新しい話し手でスタート', pages_game_url, class: 'btn btn-block btn-info btn-lg' %>
                </div>
                </br>
                <p>STEP3まで終わったら、進路のはなしをしよう、へ進んでください。</p>

                <div class="top-btn">
                    <%= link_to '進路のはなしをしよう', pages_future_url, class: 'btn btn-block btn-info btn-lg' %>
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>
</br></br>

app/views/pages/deeply.html.erb
<%
=begin%>
<h2>もっと掘りさげたいとき</h2>

<h2>聞き手の方へ</h2>
<p>・</p>
<p></p>
</br>
<%
=end%>

app/views/pages/philo.html.erb
</br>
<h2>哲学しつもん探し</h2>
<div class="container container-m">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h5>つぎのテーマから哲学的な問い（しつもん）をひとりずつ出してください。</h5>
            <h6>哲学的な問いの例</h6>
            <h6>テーマ：病気</h6>
            <h6>いつから病気があるのか／病気の何が問題か／完全に病気でない人はいるのか／病は気からは本当か／病的と病気はどう違うか／感染症は他の病気とどう違うか　など</h6>
            </br>
            <div class="category">
                <h2> <%= %w[宇宙 海 コンピュータ 動物 スマホ 健康 都道府県 アメリカ 神社 祭り 歌 武器 テスト 季節 歴史 米 酒 ペット 葬儀 野球 オリンピック 映画 靴].sample %>
                </h2>
            </div>
            </br>
            <h6>タイマーか時計で1分間測ってください。</h6>
            <h6>沈黙が続いても、気にしないで考え続けてください。</h6>
            <h6>誰もがうなる深い問いを出せた人には拍手。</h6>
            <h6>質問を考える能力を高めると、人の話を理解しようとするとき、適切な質問ができるようになります。</h6>
            <div class="top-btn">
                <%= link_to 'テーマを選びなおす', pages_philo_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
            <div class="img">
                <img class="about-img" src="/yubi.jpg">
            </div>
            </br>
            <h5>ウォーミングアップが終わったら、</br>対話ゲームを始めてください。</h5>
            <div class="top-btn">
                <%= link_to 'ゲームスタート', pages_game_url, class: 'btn btn-block btn-info btn-lg' %>
            </div>


        </div>
        <div class="col-md-3">

        </div>
    </div>
</div>



</br>
</br>

app/views/pages/reflection2.html.erb
<h2>聞き手の振り返り</h2>

<div class="img">
    <img class="about-img" src="/yubi2.jpg">
</div>

<div class="container container-m">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <div class="reflection">
                <p>質問をしてみて</br>
                    </br>
                    ・話し手の話をきちんと聞けましたか</br>
                    </br>
                    ・質問で掘り下げされましたか</br>
                    </br>
                    ・話し手の話した内容で初めて知ったことは？</br>
                    </br>
                    などについて話してください。</br>
                    </br>
                    聞き手が全員話したら、次へ進んでください。

                </p>

            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>
</br>
<div class="top-btn">


    <%= link_to '振り返り終了', pages_close_url, class: 'btn btn-block btn-info btn-lg' %>
</div>
</br>

app/views/pages/shiritori.html.erb
</br>
<h2>しりとり</h2>

</h5>
<div class="container container-m">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h5>つぎのテーマでしりとりをします。
                <div class="category">
                    <h2> <%= %w[行ったことがある場所 食べもの 地名 動物の名前 植物の名前 身につけるもの 人の名前 スポーツ選手の名前 スーパーマーケットで売っているもの].sample %>
                    </h2>
                </div>
                </br>

                <h6>下の文字からスタートしてください。</br>タイマーか時計で1分間測ってください。</h6>
                <div class="category">
                    <h1> <%= %w[あ ぎ て き り へ ぱ む ひ ば が た と よ み れ ろ わ い う え お か さ み め ら し な に ぬ ね の].sample %>
                    </h1>
                </div>
                </br>
                <div class="top-btn">
                    <%= link_to 'テーマを選びなおす', pages_shiritori_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>
                <div class="img">
                    <img class="about-img" src="/yubi.jpg">
                </div>
                </br>
                <h6>ウォーミングアップが終わったら、</br>対話ゲームを始めてください。</h6>
                <div class="top-btn">

                    <%= link_to 'ゲームスタート', pages_game_url, class: 'btn btn-block btn-info btn-lg' %>
                </div>
                <div class="top-btn">

                    <%= link_to '哲学しつもん探しへ', pages_philo_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>

        </div>
        <div class="col-md-3">

        </div>
    </div>
</div>



</br>
</br>

app/views/pages/start.html.erb
<%
=begin%>
<h1>ゲームをはじめる</h1>

<div class="img">
    <img class="about-img" src="/yubi.jpg">
</div>
<h2>1.大人が話し手となってはじめる</h2>

<p>最初に、親（大人）が話し手となって対話をします。</br>
    話し手は、選ばれたテーマについて、自分の考えを話します。</br>
    そのとき、「①考えと②そう考える理由」を話してください。</br>
    </br>
    理由を話すのを忘れていたら他の人が教えてあげてください。</br>
    話す時間は3分程度が目安です。</br>
    また、選ばれたテーマが話しにくい場合、変更することも可能です。</p>

</br>
<h2>2.聞き手は順番に質問する</h2>
<p>次に、話し手以外の参加者は、話し手に対し、質問をしていきます。</br>
    </br>
    質問は、話し手の考えを整理し、他の人に理解してもらうための大事なステップです。</br>

    一人ずつ、ランダムに設定される質問カードを見て、話し手に質問をしてください。</br>
    </br>
    このとき、質問以外のこと、自分の考えや話し手への評価は絶対に話さないでください。</br>
    これは、このゲームの中で最も大事なルールです。
    「私もそう思う」や「いい考えだと思う」など相手を認めるような表現もダメです。</p>
</br>
<h2>3.話し手を交代する</h2>
<p>大人が終わったら、子どもが話し手となります。</br>
    話し手が対話のテーマについて、自分の考えを話します。</br>
    質問の仕方は最初の場合と同じです。</p>

</br>
</br>
<p>趣旨や流れを理解しましたか？</br>
    </br>
    確認できたら、対話ゲームを始めましょう。</br>
    </br>
<div class="img">
    <img class="about-img" src="/hanashi3.jpg">
</div>
</br>
スムーズにいかないときは、「話し手が話しにくそうにしているとき」や「もっと話を掘り下げたいとき」のボタンがありますので心配はいりません。</br>
</br>
初めてこのゲームをする場合はウォーミングアップから始めましょう。</p>
</br>

<div class="top-btn">
    <%= link_to 'スタート', pages_game_url, class: 'btn btn-info btn-lg' %></div>
<div class="top-btn">
    <%= link_to 'ウォーミングアップ', pages_shiritori_url, class: 'btn btn-info btn-lg' %></div>
<%
=end%>

app/views/pages/top.html.erb
<div class="about-main">

    <div class="img">
        <img class="top-img" width="60%" src="/logo.png">
    </div>
    </br>

    <div class="container container-m">
        <div class="row">
            <div class="col-md-4 warm">

                <p class="haikei2">humaは、家族で進路のことなど大事な話をするときに、親も子も感情的にならずに、
                    素直に話ができる関係性をつくるための対話サポートアプリです。</p>

            </div>
            <div class="col-md-4 warm">


                <p class="haikei2">画面の指示にしたがって、話をしたり、質問したりするだけで、
                    お互いの価値観を共有したり、さらに深めあったりすることができます。</p>
            </div>
            <div class="col-md-4 warm">
                <p class="haikei2">進路の決断に正解はありませんが、子どもが自分の考えをよく整理したうえで、決断するためのサポートをします。</p>
            </div>
        </div>
    </div>

    </br></br>
    <div class="container container-m">
        <div class="row">
            <div class="col-md-3 warm">
                <img src="/wood.png" height="80" alt="img" class="img-fulied">
                <div class="top-btn">
                    <%= link_to 'わたしたちの思い', pages_about_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>
            </div>
            <div class="col-md-3 warm">
                <img src="/cup.png" height="80" alt="img" class="img-fulied">
                <div class="top-btn">
                    <%= link_to '使いかた', pages_usage_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>
            </div>
            <div class="col-md-3 warm">
                <img src="/shoes.png" height="80" alt="img" class="img-fulied">
                <div class="top-btn">
                    <%= link_to 'ウォーミングアップ', pages_warmup_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>
            </div>
            <div class="col-md-3 warm">
                <img src="/cycle.png" height="80" alt="img" class="img-fulied">
                <div class="top-btn">
                    <%= link_to 'ゲームをはじめる', pages_game_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
                </div>
            </div>
        </div>
    </div>
</div>

</br></br>

app/views/pages/warmup.html.erb
<h2>ウォーミングアップ</h2>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <img src="/shiritorigame.png" alt="img" class="img-fulied">
            <p class="step">指定されたテーマでしりとりをします。</p>
            <p class="step">時計を用意してください。制限時間は1分です。何個出せるでしょうか。</p>
            <p class="step"></p>
            <div class="top-btn">
                <%= link_to 'しりとりゲームへ', pages_shiritori_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>
        <div class="col-md-6 warm">
            <img src="/tetsugaku.png" alt="img" class="img-fulied">
            <p class="step">哲学的な質問とは、簡単に答えが出ない根源的な問いのこと。</p>
            <p class="step">身近なことばから、哲学的な問いをさがすには、世界の見る視点を変える必要があります。</p>
            <p class="step">無理矢理に考えてみることで、今まで気づかなかった視点が得られるかもしれません。</p>
            <div class="top-btn">
                <%= link_to '哲学しつもん探しへ', pages_philo_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>

    </div>
</div>
<div class="top-btn">
    <%= link_to 'ゲームを開始する', pages_game_url, class: 'btn btn-block btn-info btn-lg' %>
</div>

app/views/questions/random.html.erb
</br>
<div class="img">
    <img class="about-img" src="/humalogo.png">
</div>

<h2>いまのテーマ</h2>
<div class="category">
    <h2><%= @question.theme.name %></h2>
</div>
</br>
</br>
</br>
<h2>ヒントの質問</h2>
<div class="question fade-in-bottom">
    <h2><%= @question.name %></h2>
</div>
</br>
</br>


<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <div class="top-btn">
                <%= link_to '質問を変えたいとき／次の質問者', theme_questions_random_url(theme_id: @question.theme_id), class: 'btn btn-block btn-info btn-lg' %>
            </div>
        </div>
        <div class="col-md-6 warm">
            <!-- Button trigger modal -->
            <div class="top-btn">
                <button type="button" class="btn btn-block btn-info btn-lg" data-toggle="modal" data-target="#exampleModal">
                    基本の質問カードをひく
                </button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">基本の質問カード</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="category">
                                <h2> <%= %w[なぜ_____と思うのですか  _____についてもっとくわしく教えてください  たとえ_____であってもそういえますか？  そもそも_____って何ですか  ______と思う根拠は何ですか].sample %>
                                </h2>
                            </div>
                            </br>
                            <h6>余白____は質問者が補ってください。</h6>
                            <h6>話し手の答えに対し、4〜5回追いかけ質問を繰り返すと深く掘り下げることができます。</h6>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-info" data-dismiss="modal">閉じる</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <div class="top-btn">
                <%= link_to '話しにくいと感じたら', pages_deadlock_url, class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>

        <div class="col-md-6 warm">
            <div class="top-btn">
                <%= link_to '前のページへもどる', :back , class: 'btn btn-block btn-outline-secondary btn-lg' %>
            </div>
        </div>
    </div>

</div>

</br> </br>
<div class="essential">
    <div class="container container-m">
        <div class="row">
            <div class="col-md-3">
                <h3 class="haikei5">大事なルール</h3>
                <p class="step">人の話をちゃんと聞く</p>
                <p class="step">お互いの考え方を尊重する</p>
                <p class="step">相手に伝わるように話す</p>
            </div>

            <div class="col-md-4">

                <h3 class="haikei5">話すときに気をつけること</h3>
                <p class="step">自分の「考え」と「そう考える理由」を話す</p>
                <p class="step">言いたくないことは言わなくていい</p>
                <p class="step">慌てて話さず、じっくり考える</p>
            </div>
            <div class="col-md-5">

                <h3 class="haikei5">質問するときに気をつけること</h3>
                <p class="step">質問以外の発言はしない</p>
                <p class="step">相手のことを理解しようとする気持ちで聞く</p>
                <p class="step">無理に聞き出そうとしない</p>

            </div>

        </div>
    </div>
</div>

</br>
</br>

<h4> 全員が質問し終わったら</h4>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <p class="haikei2">このテーマについて掘り下げが足りない時は、２周目、３周目の質問をしてください。</p>
        </div>
        <div class="col-md-6 warm">
            <p class="haikei2">今の話し手が終了するときは、対話ゲームの振りかえりをしてください。</p>
        </div>
    </div>
</div>

</br>
<div class="img">
    <img class="about-img" src="/hoshi.jpg">
</div>
</br>
<div class="top-btn">
    <%= link_to '話し手の振りかえり', pages_reflection_url, class: 'btn btn-block btn-info btn-lg' %>

</div></br>

app/views/themes/question1.html.erb
<h2>テーマ</h2>
<div class="category">
    <h2><%= @question.theme.name %></h2>
</div>
</br>
</br>
<div class="category">
    <h2> <%= %w[なぜ_____と思うのですか _____についてもっとくわしく教えてください _____であってもそういえますか？].sample %>
    </h2>
</div>

app/views/themes/random.html.erb
</br>
<div class="img">
    <img class="about-img" src="/humalogo.png">
</div>
</br>
<div class="container container-m">
    <div class="row">
        <div class="col-md-4 warm">
            <p class="rule3">今から話し手は、テーマについて話します。</br>
                すぐに話し出さずに、30秒程度「自分の考えとそう考える理由」を整理してから、話し始めてください。</p>
            </br>
        </div>
        <div class="col-md-4 warm">
            <p class="rule3">話し手の話が終わったら、聞き手は一人ずつ、質問カードを引いて、話し手に質問してください。</br>
                質問は話し手の考えの背景が理解できるまで続けてください。</p>
            </br>
        </div>
        <div class="col-md-4 warm">

            <p class="rule3">質問カードは２種類あります。</br>
                基本の質問カードは、「なぜ____と思うのですか」など穴埋めになっているので、言葉を補って質問します。</br>
                もっと掘り下げたいときは、ヒントの質問カードを使ってください。</p>
        </div>
    </div>
</div>
</br>
<h2>テーマ</h2>

<div class="category fade-in-bottom">
    <h2><%= @theme.name %></h2>
</div>
</br>


</br>

</div>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <p class="haikei2">最初は基本の質問カードで質問してください</br></p>

            <!-- Button trigger modal -->
            <div class="top-btn">
                <button type="button" class="btn btn-block btn-info btn-lg" data-toggle="modal" data-target="#exampleModal">
                    基本の質問カードをひく
                </button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">基本の質問カード</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="category">
                                <h2> <%= %w[なぜ_____と思うのですか  _____についてもっとくわしく教えてください  たとえ_____であってもそういえますか？  そもそも_____って何ですか  ______と思う根拠は何ですか].sample %>
                                </h2>
                            </div>
                            </br>
                            <h6>余白____は質問者が補ってください。</h6>
                            <h6>話し手の答えに対し、4〜5回追いかけ質問を繰り返すと深く掘り下げることができます。</h6>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-info" data-dismiss="modal">閉じる</button>

                        </div>
                    </div>
                </div>
            </div>


            <%
=begin%>
            <div class="top-btn">
                <div class="top-btn2">
                    <%= link_to '基本の質問カードをひく', questions_question1_url, class: 'btn btn-info btn-lg' %>
                </div>
            </div>
            <%
=end%>
        </div>
        <div class="col-md-6 warm">
            <p class="haikei2">もっと深めたいときはヒントの質問カードを使ってください</p>
            <div class="top-btn">
                <%= link_to 'ヒントの質問カードをひく', theme_questions_random_url(theme_id: @theme.id), class: 'btn btn-block btn-info btn-lg' %>
            </div>
        </div>

    </div>
</div>

<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <%
=begin%>
            <h5>話しにくそうにしているとき</h5>
            <%
=end%>
            <div class="top-btn">

                <%= link_to '話しにくいと感じたら', pages_deadlock_url, class: 'btn btn-block btn-outline-secondary btn-lg' %></div>

        </div>
        <div class="col-md-6 warm">
            <%
=begin%>
            <h5>テーマを選びなおしたいとき</h5>
            <%
=end%>
            <div class="top-btn">

                <%= link_to 'テーマの選び直し', category_themes_random_url(@theme.category), class: 'btn btn-block btn-outline-secondary btn-lg' %>

            </div>
        </div>
    </div>
</div>
</br></br>

<div class="essential">
    <div class="container container-m">
        <div class="row">
            <div class="col-md-3">
                <h3 class="haikei5">大事なルール</h3>
                <p class="step">人の話をちゃんと聞く</p>
                <p class="step">お互いの考え方を尊重する</p>
                <p class="step">相手に伝わるように話す</p>
            </div>

            <div class="col-md-4">

                <h3 class="haikei5">話すときに気をつけること</h3>
                <p class="step">自分の「考え」と「そう考える理由」を話す</p>
                <p class="step">言いたくないことは言わなくていい</p>
                <p class="step">慌てて話さず、じっくり考える</p>
            </div>
            <div class="col-md-5">

                <h3 class="haikei5">質問するときに気をつけること</h3>
                <p class="step">質問以外の発言はしない</p>
                <p class="step">相手のことを理解しようとする気持ちで聞く</p>
                <p class="step">無理に聞き出そうとしない</p>

            </div>

        </div>
    </div>
</div>


</br>
</br>
<h4> 全員が質問し終わったら</h4>
<div class="container container-m">
    <div class="row">
        <div class="col-md-6 warm">
            <p class="haikei2">このテーマについて掘り下げが足りない時は、２周目、３周目の質問をしてください。</p>
        </div>
        <div class="col-md-6 warm">
            <p class="haikei2">今の話し手が終了するときは、対話ゲームの振りかえりをしてください。</p>
        </div>
    </div>
</div>

</br>
<div class="img">
    <img class="about-img" src="/hoshi.jpg">
</div>
</br>
<div class="top-btn">
    <%= link_to '話し手の振りかえり', pages_reflection_url, class: 'btn btn-block btn-info btn-lg' %>
</div>

</br></br>